# permissions for end users to edit imagevulnerabilities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagevulnerability-editor-role
rules:
- apiGroups:
  - khulnasoft-lab.github.io
  resources:
  - imagevulnerabilities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - khulnasoft-lab.github.io
  resources:
  - imagevulnerabilities/status
  verbs:
  - get
